image: node:latest

services:
  - redis:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/rbrian/hello-node .
    - docker push registry.gitlab.com/rbrian/hello-node
