# container-centric node webapp CI/CD pipeline
# 1. builds and pushes a container
# 2. tests using "dev artifacts" npm, package.json, and test.js
# 3. re-pushes container to cloud

stages:
  - build
  - test
  - containerize
  - staging
  - deploy

variables:
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGISTRY_IMAGE: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CI_PROJECT_NAME:$CI_BUILD_REF_SLUG

build:
  stage: build
  image: docker:dind
  variables:
    GIT_STRATEGY: fetch
  before_script:
    - docker info
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  variables:
    GIT_STRATEGY: none
  services:
    - cassandra
  script:
    # hack to wait for cassandra
    - sleep 5
    - cd /usr/src/app
    - npm install --only=dev
    - npm test

# WIP
staging_aws:
  stage: staging
  image:
    name: anigeo/awscli
    entrypoint: ["/bin/sh", "-c"]
  variables:
    GIT_STRATEGY: none
  environment:
    name: staging
    url: http://staging.example.com/
  before_script:
    - '[ -z "$AWS_ACCESS_KEY" ] && { echo AWS_ACCESS_KEY missing; exit 1; }'
    - '[ -z "$AWS_SECRET_ACCESS_KEY" ] && { echo AWS_SECRET_ACCESS_KEY missing; exit 1; }'
  script:
    - aws --version
    - aws ecs deploy
  only:
    - master
  when: manual

# WIP
deploy_aws:
  stage: deploy
  image:
    name: anigeo/awscli
    entrypoint: ["/bin/sh", "-c"]
  variables:
    GIT_STRATEGY: none
  environment:
    name: production
    url: https://example.com/
  script:
    - aws ecs help
  only:
    - master
  when: manual
