image: node:latest

services:
  - redis:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build
  - staging
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

staging:
  stage: staging
  image: cgswong/aws:aws
  environment:
    name: staging
    url: http://staging.example.com/
  script:
    - which aws || true
  only:
    - master

deploy:
  stage: deploy
  image: cgswong/aws:aws
  environment:
    name: production
    url: https://example.com/
  script:
    - which aws || true
  when: manual
  only:
    - master
