image: node:latest

services:
  - redis:latest

cache:
  paths:
  - node_modules/

test:
  script:
   - npm install
   - npm test

build:
  script:
    - echo create container

deploy:
  script:
    - echo deploy to GCS or AWS-ECS-ACBAR
