stages:
  - build
  - test
  - staging
  - deploy

cache:
  paths:
    - /var/lib/docker

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

test:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - npm test

staging:
  stage: staging
  image: anigeo/awscli
  environment:
    name: staging
    url: http://staging.example.com/
  script:
    - --version
    - configure
  only:
    - master

production:
  stage: deploy
  image: anigeo/awscli
  environment:
    name: production
    url: https://example.com/
  script:
    - help
  when: manual
  only:
    - master
