image: docker:latest

services:
  - docker:dind
  - redis:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

test:
  script:
    - docker exec $CI_REGISTRY_IMAGE npm test

deploy:
  script:
    - echo deploy to GCS or AWS-ECS-ACBAR
