image: node:latest

services:
  - redis:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  script:
    - npm install
    - echo create container

test:
  script:
    - echo run node test.js in container

deploy:
  script:
    - echo deploy to GCS or AWS-ECS-ACBAR
