image: node:latest

services:
  - redis:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  script:
    - echo tbd
