stages:
  - build
  - test
  - staging
  - deploy

variables:
  AWS_DEFAULT_REGION: us-west-2

cache:
  # XXX unsure if this helps
  paths:
    - /var/lib/docker

build:
  stage: build
  image: docker
  services:
    - docker:dind
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master

test:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - npm test

staging:
  stage: staging
  image:
    name: anigeo/awscli
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: staging
    url: http://staging.example.com/
  before_script:
    - '[ -z "$AWS_ACCESS_KEY" ] && { echo AWS_ACCESS_KEY missing; exit 1; }'
    - '[ -z "$AWS_SECRET_ACCESS_KEY" ] && { echo AWS_SECRET_ACCESS_KEY missing; exit 1; }'
  script:
    - aws --version
    - aws ecs deploy
  only:
    - master

production:
  stage: deploy
  image:
    name: anigeo/awscli
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: production
    url: https://example.com/
  script:
    - aws ecs help
  when: manual
  only:
    - master
